BOARD_TYPE = uno
ARDUINO_PORT = /dev/ttyACM0
ARDUINO_LIBS = Adafruit_Unified_Sensor Adafruit_BME280_Library DHT_sensor_library Adafruit_MLX90614_Library Servo Wire Firmata SPI18
ARDUINO_DIR = /usr/share/arduino
include ~/sketchbook/Arduino.mk
