BOARD_TYPE = uno
ARDUINO_PORT = /dev/ttyACM0
ARDUINO_LIBS = Adafruit_Sensor_Master Adafruit_BME280_Library DHT_sensor_library Adafruit_MLX90614_Library Wire SPI#Servo Wire Firmata SPI18
#ARDUINO_DIR = /usr/share/arduino
ARDUINO_DIR = /home/pi/arduino-1.8.3
include ~/sketchbook/Arduino.mk
